version: '3.8'
services:
  flask-app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - elasticsearch
    environment:
      - ELASTIC_SEARCH_HOST=http://elasticsearch:9200
      - ELASTIC_KEY=my_password
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    volumes:
      - ./elasticsearch-logs:/usr/share/elasticsearch/logs
    environment:
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=my_password
    ports:
      - "9200:9200"
