version: '3.8'
services:
  flask-app:
    build: .
    ports:
      #- "5000:5000"
      - "8000:8000"
    depends_on:
      - elasticsearch
    environment:
      - PORT=8000 
      - ELASTIC_SEARCH_HOST=http://elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    volumes:
      - ./elasticsearch-logs:/usr/share/elasticsearch/logs
    environment:
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
