"""create channels and users tables

Revision ID: 2c8265383642
Revises: 
Create Date: 2024-09-20 14:39:55.253824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
import uuid


# revision identifiers, used by Alembic.
revision: str = '2c8265383642'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, nullable=False),
        sa.Column('user_email', sa.String(200), nullable=False),
        sa.Column('user_name', sa.String(100), nullable=False),
        sa.Column('user_password', sa.String(255), nullable=False),
        sa.Column('user_profile_picture_url', sa.String(255), nullable=True)
    )
    op.create_table(
        'channels',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, nullable=False),
        sa.Column('channel_name', sa.String(50), nullable=False),
        sa.Column('channel_description', sa.String(100), nullable=False),
        sa.Column('channel_color', sa.String(50), nullable=True),
        sa.Column('user_id', UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=False)
    )
    
    op.create_table(
        'channel_user_association',
        sa.Column('user_id', UUID(as_uuid=True), sa.ForeignKey('users.id'), primary_key=True),
        sa.Column('channel_id', UUID(as_uuid=True), sa.ForeignKey('channels.id'), primary_key=True)
    )
    
    op.create_table(
        'channel_messages',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=uuid.uuid4),
        sa.Column('channel_id', UUID(as_uuid=True), sa.ForeignKey('channels.id'), nullable=False),
        sa.Column('sender_id', UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('content', sa.Text, nullable=False),
        sa.Column('timestamp', sa.DateTime, default=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_messages')
    op.drop_table('channel_user_association')
    op.drop_table('channels')
    op.drop_table('users')
    # ### end Alembic commands ###
