"""Add new fields to User model

Revision ID: 7acf726795ac
Revises: 2c8265383642
Create Date: 2024-11-05 09:12:28.526662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import datetime

# revision identifiers, used by Alembic.
revision: str = '7acf726795ac'
down_revision: Union[str, None] = '2c8265383642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('create_date', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('users', sa.Column('password_expire_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'password_expire_date')
    op.drop_column('users', 'create_date')
    op.drop_column('users', 'last_login_date')
    op.alter_column('channels', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('channel_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('channel_messages', 'sender_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('channel_messages', 'channel_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
