"""implement thread suggestion table and - realtion to channel messages and direct message

Revision ID: b44e5b004e80
Revises: 871a774cb305
Create Date: 2024-11-27 13:23:20.492061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44e5b004e80'
down_revision: Union[str, None] = '871a774cb305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_type', sa.String(), nullable=False),
    sa.Column('channel_message_id', sa.UUID(), nullable=True),
    sa.Column('direct_message_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thread_suggestion', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_message_id'], ['channel_messages.id'], ),
    sa.ForeignKeyConstraint(['direct_message_id'], ['direct_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_messages')
    # ### end Alembic commands ###
