"""Added tables

Revision ID: d68b72e9cd08
Revises: 7acf726795ac
Create Date: 2024-11-08 15:54:16.911485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd68b72e9cd08'
down_revision: Union[str, None] = '7acf726795ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('users', sa.Column('role_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.alter_column('channel_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
